iso_url = "https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.0-x86_64-dvd.iso"
iso_checksum_type = "sha256"
iso_checksum = "55dbf904b35969be9f6d96f042b7470d1a3cb5c953bba47ab8f79740560d8a8d"
vm_name = "packer-rockylinux9-g2"
disk_size = "70000"
disk_additional_size = ["150000"]
switch_name = "vSwitch"
output_directory = "output-rockylinux9"
output_vagrant = "./vbox/packer-rockylinux9-g2.box"
vlan_id = ""
memory = "4096"
cpus = "2"
vagrantfile_template = "./vagrant/hv_rockylinux9_g2.template"
ssh_password = "password"
provision_script_options = "-z false"
boot_command = "c  setparams 'kickstart' <enter> linuxefi /images/pxeboot/vmlinuz inst.stage2=hd:LABEL=Rocky-9-0-x86_64-dvd inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/gen2-rockylinux9/ks.cfg<enter> initrdefi /images/pxeboot/initrd.img<enter> boot<enter>"
ansible_override = "variables/rockylinux9.yml"
