iso_url = "http://mirror.netcologne.de/oracle-linux/OL8/u5/x86_64/OracleLinux-R8-U5-x86_64-dvd.iso"
iso_checksum_type = "sha256"
iso_checksum = "45939e85542c19dd519aaad7c4dbe84a6fcadfaca348245f92ae4472fc7f50ac"
vm_name = "packer-oraclelinux85-g2"
disk_size = "70000"
disk_additional_size = ["150000"]
switch_name = "vSwitch"
output_directory = "output-oraclelinux85"
output_vagrant = "./vbox/packer-oraclelinux85-g2.box"
vlan_id = ""
memory = "4096"
cpus = "2"
vagrantfile_template = "./vagrant/hv_oraclelinux85_g2.template"
ssh_password = "password"
provision_script_options = "-z false"
boot_command = "c  setparams 'kickstart' <enter> linuxefi /images/pxeboot/vmlinuz inst.stage2=hd:LABEL=OL-8-5-0-BaseOS-x86_64 inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/gen2-oraclelinux8/ks.cfg<enter> initrdefi /images/pxeboot/initrd.img<enter> boot<enter>"
ansible_override = "variables/oraclelinux8.yml"
